### ISSUE TITLE
can not compile netclient for arm64

### ISSUE THREAD

**Issue by changchichung** [gravitl/netmaker#140]
I can't add to netmaker with netclient.arm64 from release page with these error
```
root@GL-MV1000-40:~/git# ./netclient.arm64  -c install -t bG9jYnM0JNazh6MkhVdjZnU3w= -s ws.com:50051
Beginning agent installation.
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/gravitl/netmaker/netclient/functions.Install(0x5e9aac, 0x6, 0x5ebc47, 0x8, 0x7fc53e1eb9, 0x13, 0x5ecb5c, 0x9, 0x400011dc00, 0x7fc53e1e7d, ...)
	/home/mkasun/sandbox/netmaker/netclient/functions/common.go:96 +0x29a4
main.main()
	/home/mkasun/sandbox/netmaker/netclient/main.go:111 +0xc54
root@GL-MV1000-40:~/git# 

```
OS info
```
root@GL-MV1000-40:~/git# cat /etc/os-release 
NAME="OpenWrt"
VERSION="19.07.0-rc1"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt 19.07.0-rc1"
VERSION_ID="19.07.0-rc1"
HOME_URL="https://openwrt.org/"
BUG_URL="https://bugs.openwrt.org/"
SUPPORT_URL="https://forum.openwrt.org/"
BUILD_ID="r10649-c4fdb377a2"
OPENWRT_BOARD="mvebu/cortexa53"
OPENWRT_ARCH="aarch64_cortex-a53"
OPENWRT_TAINTS="override"
OPENWRT_DEVICE_MANUFACTURER="OpenWrt"
OPENWRT_DEVICE_MANUFACTURER_URL="https://openwrt.org/"
OPENWRT_DEVICE_PRODUCT="Generic"
OPENWRT_DEVICE_REVISION="v0"
OPENWRT_RELEASE="OpenWrt 19.07.0-rc1 r10649-c4fdb377a2"
root@GL-MV1000-40:~/git# 
```

so I want to compile netclient but go build with errors
```
chchang@administrator-ThinkPad-T470:~/git/netmaker/netclient.bak$ GOARCH=arm64 GOOS=linux go build . 
main.go:5:9: no required module provides package github.com/gravitl/netmaker/netclient/functions; to add it:
	go get github.com/gravitl/netmaker/netclient/functions
chchang@administrator-ThinkPad-T470:~/git/netmaker/netclient.bak$ go get github.com/gravitl/netmaker/netclient/functions
go get github.com/gravitl/netmaker/netclient/functions: no matching versions for query "upgrade"
chchang@administrator-ThinkPad-T470:~/git/netmaker/netclient.bak$ 
```

frustrated with implementing netClient on openWrt  :face_with_head_bandage:

**Comment by changchichung** [comment]
damn , can rename the "netclient" folder ...
