### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by WMP** [gravitl/netmaker#2353]
### What happened?

I have fresh installed v.0.20.0, and always after add new host, when i execute command 
```
sudo netclient join -t ...
```

i have this error. Refresh show on list new node, and all works. 

### Version

v0.20.0

### What OS are you using?

Linux

### Relevant log output

```shell
Unexpected Application Error!
Cannot read properties of undefined (reading 'name')
TypeError: Cannot read properties of undefined (reading 'name')
    at sorter (https://dashboard.netmakerDOMAIN/assets/index-1ddff8c4.js:832:99650)
    at https://dashboard.netmakerDOMAIN/assets/index-1ddff8c4.js:420:25613
    at Array.sort (<anonymous>)
    at G$ (https://dashboard.netmakerDOMAIN/assets/index-1ddff8c4.js:420:25499)
    at https://dashboard.netmakerDOMAIN/assets/index-1ddff8c4.js:485:3798
    at Object.dD [as useMemo] (https://dashboard.netmakerDOMAIN/assets/index-1ddff8c4.js:38:23921)
    at Fn.useMemo (https://dashboard.netmakerDOMAIN/assets/index-1ddff8c4.js:9:6208)
    at Ebe (https://dashboard.netmakerDOMAIN/assets/index-1ddff8c4.js:485:3786)
    at pO (https://dashboard.netmakerDOMAIN/assets/index-1ddff8c4.js:38:19538)
    at ZR (https://dashboard.netmakerDOMAIN/assets/index-1ddff8c4.js:40:1571)
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by Aceix** [comment]
Fixed in upcoming release. Refreshing the page should allow you proceed
