### ISSUE TITLE
Error with join network with freebsd(pfsense）

### ISSUE THREAD

**Issue by Error996** [gravitl/netmaker#554]
```
2021/12/16 16:46:30 [netclient] node created on remote server...updating configs
2021/12/16 16:46:30 [netclient] Node is marked as PENDING.
2021/12/16 16:46:30 [netclient] Awaiting approval from Admin before configuring WireGuard.
2021/12/16 16:46:31 [netclient] retrieving peers
2021/12/16 16:46:31 [netclient] starting wireguard
2021/12/16 16:46:31 [netclient] writing wg conf file to: /etc/netclient/config/nm-Home.conf
2021/12/16 16:46:31 [netclient] failed to create wireguard interface
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8efe94]

goroutine 39 [running]:
github.com/gravitl/netmaker/netclient/ncutils.RunCmd.func1({0xaf3c28, 0xc000254720}, 0xc0002a62c0)
        /root/netmaker/netclient/ncutils/netclientutils_freebsd.go:34 +0x54
created by github.com/gravitl/netmaker/netclient/ncutils.RunCmd
        /root/netmaker/netclient/ncutils/netclientutils_freebsd.go:32 +0x1c5
```

```
Usage: wg <cmd> [<args>]

Available subcommands:
  show: Shows the current configuration and device information
  showconf: Shows the current configuration of a given WireGuard interface, for use with `setconf'
  set: Change the current configuration, add peers, remove peers, or change peers
  setconf: Applies a configuration file to a WireGuard interface
  addconf: Appends a configuration file to a WireGuard interface
  syncconf: Synchronizes a configuration file to a WireGuard interface
  genkey: Generates a new private key and writes it to stdout
  genpsk: Generates a new preshared key and writes it to stdout
  pubkey: Reads a private key from stdin and writes a public key to stdout
You may pass `--help' to any of these subcommands to view usage.
```

**Comment by Error996** [comment]
need pfsense version

**Comment by Error996** [comment]
Work Good on OPNsense,Close

**Comment by afeiszli** [comment]
@Error996 on OpnSense can you try "netclient pull -n Home" and see if wg gets set?
on PFSense I see "node is marked as Pending". This means it requires approval in the UI. Did you approve it? Otherwise, try with a new key (usually means key is invalid)

**Comment by Error996** [comment]
opnsense:  wg not gets set
pfsense: i did approve it

**Comment by afeiszli** [comment]
I believe the IsPending functionality had some bugs in the prior version. Please let us know if you are still experiencing the issue or if we can close.

**Comment by varoudis** [comment]
This is still a problem. Any ideas?

```
[2.5.2-RELEASE][admin@pfSense.stroumfospito.local]/root: /usr/sbin/netclient join -t XXXXXX==
[netclient] 2022-09-02 12:30:48 joining netmain at api.nm.XXXXX.nip.io:443
[netclient] 2022-09-02 12:30:49 network: netmain node pfSensestroumfospitolocal is using port 51821
[netclient] 2022-09-02 12:30:50 error running command: route show default
[netclient] 2022-09-02 12:30:50
[netclient] 2022-09-02 12:30:50 error setting route for netmaker: error getting default route: signal: killed
[netclient] 2022-09-02 12:30:50 network: netmain certificates/key saved
[netclient] 2022-09-02 12:30:50 starting wireguard
[netclient] 2022-09-02 12:30:52 error running command: wg-quick up /etc/netclient/config/nm-netmain.conf
[netclient] 2022-09-02 12:30:52
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x70af9e]

goroutine 32 [running]:
github.com/gravitl/netmaker/netclient/ncutils.RunCmd.func1()
	/home/runner/work/netmaker/netmaker/netclient/ncutils/netclientutils_freebsd.go:42 +0x3e
created by github.com/gravitl/netmaker/netclient/ncutils.RunCmd
	/home/runner/work/netmaker/netmaker/netclient/ncutils/netclientutils_freebsd.go:40 +0x1aa
```



```
[2.5.2-RELEASE][admin@pfSense.stroumfospito.local]/root: /usr/sbin/netclient daemon
[netclient] 2022-09-02 12:34:44 [daemon.go-47] Daemon(): netclient daemon started -- version: v0.15.0
[netclient] 2022-09-02 12:34:44 [clientconfig.go-22] UpdateClientConfig(): checking for netclient updates...
[netclient] 2022-09-02 12:34:44 [clientconfig.go-48] UpdateClientConfig(): finished updates
[netclient] 2022-09-02 12:34:44 [mqpublish.go-26] Checkin(): starting checkin goroutine
[netclient] 2022-09-02 12:34:44 [daemon.go-93] startGoRoutines(): initializing network netmain
[netclient] 2022-09-02 12:34:44 [netclientutils_freebsd.go-46] RunCmd(): error running command: wg-quick up /etc/netclient/config/nm-netmain.conf
[netclient] 2022-09-02 12:34:44 [netclientutils_freebsd.go-47] RunCmd():
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x70af9e]

goroutine 18 [running]:
github.com/gravitl/netmaker/netclient/ncutils.RunCmd.func1()
	/home/runner/work/netmaker/netmaker/netclient/ncutils/netclientutils_freebsd.go:42 +0x3e
created by github.com/gravitl/netmaker/netclient/ncutils.RunCmd
	/home/runner/work/netmaker/netmaker/netclient/ncutils/netclientutils_freebsd.go:40 +0x1aa
```
