### ISSUE TITLE
[Bug]: Rootless Podman

### ISSUE THREAD

**Issue by runbmp** [gravitl/netmaker#959]
### What happened?

Currently attempting to run this in a rootless container:

```
[poduser@600sff netmaker]$ podman-compose up -d
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.0.1
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=netmaker', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
podman pod create --name=pod_netmaker --infra=false --share=
ecb5a3aaa9cb9383f261d4402a801e8db307819b4ff8c349b107a2ad1cd5bd74
exit code: 0
['podman', 'network', 'exists', 'netmaker_default']
podman run --name=netmaker -d --pod=pod_netmaker --label io.podman.compose.config-hash=f13fd1a0370b19acdb326f682754d65e52778e99a8f2cedff7d2c42e3206fcbc --label io.podman.compose.project=netmaker --label io.podman.compose.version=1.0.4 --label com.docker.compose.project=netmaker --label com.docker.compose.project.working_dir=/home/poduser/pods/netmaker --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=netmaker --cap-add NET_ADMIN --cap-add NET_RAW --cap-add SYS_MODULE -e SERVER_HOST=example.com -e CLIENT_MODE=off -e MASTER_KEY=mykey -e DISABLE_REMOTE_IP_CHECK=on -e GRPC_SSL=on -e NODE_ID=netmaker-server-1 -e MQ_HOST=mq -e HOST_NETWORK=off -e PORT_FORWARD_SERVICES=mq,dns,ssh -e VERBOSITY=1 -e TELEMETRY=off -v /home/poduser/pods/netmaker/dnsconfig:/root/config/dnsconfig -v /home/poduser/pods/netmaker/sqldata:/root/data --net netmaker_default --network-alias netmaker -p 51821-51830:51821-51830/udp -p 8081:8081 -p 50051:50051 -u 0:0 --sysctl net.ipv4.ip_forward=1 --sysctl net.ipv4.conf.all.src_valid_mark=1 --restart unless-stopped docker.io/gravitl/netmaker:v0.12.1
0eb7a3ca22d4e9722b962500c8fd65ce1c5d0e46aff0f9d9b241ffc1c49ed308
exit code: 0
['podman', 'network', 'exists', 'netmaker_default']
podman run --name=mq -d --pod=pod_netmaker --label io.podman.compose.config-hash=f13fd1a0370b19acdb326f682754d65e52778e99a8f2cedff7d2c42e3206fcbc --label io.podman.compose.project=netmaker --label io.podman.compose.version=1.0.4 --label com.docker.compose.project=netmaker --label com.docker.compose.project.working_dir=/home/poduser/pods/netmaker --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=mq -v /home/poduser/pods/netmaker/mosquitto.conf:/mosquitto/config/mosquitto.conf -v /home/poduser/pods/netmaker/mosquitto_data:/mosquitto/data -v /home/poduser/pods/netmaker/mosquitto_logs:/mosquitto/log --net netmaker_default --network-alias mq -p 1883:1883 -u 0:0 --restart unless-stopped docker.io/eclipse-mosquitto:2.0.14
1b213d4803a33e2a4c0a380d1635894c08df1ce2f079348a4a8e63f91cc963a4
exit code: 0
['podman', 'network', 'exists', 'netmaker_default']
podman run --name=netmaker-ui -d --pod=pod_netmaker --requires=netmaker --label io.podman.compose.config-hash=f13fd1a0370b19acdb326f682754d65e52778e99a8f2cedff7d2c42e3206fcbc --label io.podman.compose.project=netmaker --label io.podman.compose.version=1.0.4 --label com.docker.compose.project=netmaker --label com.docker.compose.project.working_dir=/home/poduser/pods/netmaker --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=netmaker-ui -e BACKEND_URL=http://192.168.29.174:8081 --net netmaker_default --network-alias netmaker-ui -p 8082:80 -u 0:0 --restart unless-stopped docker.io/gravitl/netmaker-ui:v0.12.1
WARN[0000] Failed to load cached network config: network netmaker_default not found in CNI cache, falling back to loading network netmaker_default from disk
ERRO[0000] Starting some container dependencies
ERRO[0000] "plugin type=\"bridge\" failed (add): cni plugin bridge failed: failed to allocate for range 0: 10.89.11.12 has been allocated to 0eb7a3ca22d4e9722b962500c8fd65ce1c5d0e46aff0f9d9b241ffc1c49ed308, duplicate allocation is not allowed"
Error: error starting some containers: internal libpod error
exit code: 126
podman start netmaker-ui
ERRO[0003] Unable to cleanup network for container 0eb7a3ca22d4e9722b962500c8fd65ce1c5d0e46aff0f9d9b241ffc1c49ed308: "error tearing down network namespace configuration for container 0eb7a3ca22d4e9722b962500c8fd65ce1c5d0e46aff0f9d9b241ffc1c49ed308: 1 error occurred:\n\t* plugin type=\"bridge\" failed (delete): cni plugin bridge failed: running [/usr/bin/iptables -t nat -X CNI-f74ae2aa09b6fdb9be55bbb2 --wait]: exit status 1: iptables: Too many links.\n\n\n"
ERRO[0003] Starting some container dependencies
ERRO[0003] "rootlessport listen tcp 0.0.0.0:8081: bind: address already in use"
Error: unable to start container "48a4600f7131e72bfa90e3c0d0bcaae3e0217c48261d3daa25b86cc798740b23": error starting some containers: internal libpod error
exit code: 125
```

Running `netstat -plnt` shows indeed none of the above ports seem to already be in use (unless PORT_FORWARD_SERVICES counts towards 22/5355)?
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:5355            0.0.0.0:*               LISTEN      1037/systemd-resolv
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1043/sshd: /usr/bin
tcp6       0      0 :::8111                 :::*                    LISTEN      112860/rootlessport
tcp6       0      0 :::8096                 :::*                    LISTEN      19556/rootlessport
tcp6       0      0 :::8080                 :::*                    LISTEN      107254/rootlessport
tcp6       0      0 :::6881                 :::*                    LISTEN      107254/rootlessport
tcp6       0      0 :::3000                 :::*                    LISTEN      105312/rootlessport
tcp6       0      0 :::2342                 :::*                    LISTEN      97096/rootlessport
tcp6       0      0 :::2019                 :::*                    LISTEN      189012/rootlessport
tcp6       0      0 :::5355                 :::*                    LISTEN      1037/systemd-resolv
tcp6       0      0 :::8920                 :::*                    LISTEN      19556/rootlessport
tcp6       0      0 :::5000                 :::*                    LISTEN      87900/rootlessport
tcp6       0      0 :::9155                 :::*                    LISTEN      47755/rootlessport
tcp6       0      0 :::9154                 :::*                    LISTEN      47755/rootlessport
tcp6       0      0 :::53                   :::*                    LISTEN      87900/rootlessport
tcp6       0      0 :::22                   :::*                    LISTEN      1043/sshd: /usr/bin
tcp6       0      0 :::80                   :::*                    LISTEN      189012/rootlessport
tcp6       0      0 :::443                  :::*                    LISTEN      189012/rootlessport
```

I have tried both with and without precreating the `netmaker_default` network using `podman network`

### Version

v0.12.1

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by runbmp** [comment]
Update:

I broke out each piece of the docker-compose file into separate pods.  The netmaker one appears to be trying to setup coredns stuff even though I have set under the environment area `DNS_MODE: "off"`:
```
│   [netmaker] 2022-03-24 02:05:36 connecting to sqlite                                                                                                                                                            │
│   [netmaker] 2022-03-24 02:05:36 database successfully connected                                                                                                                                                 │
│   [netmaker] 2022-03-24 02:05:36 no OAuth provider found or not configured, continuing without OAuth                                                                                                             │
│   [netmaker] 2022-03-24 02:05:36 setting iptables forward policy                                                                                                                                                 │
│   [netmaker] 2022-03-24 02:05:36 forwarding mq traffic from host port 1883 to container port 1883                                                                                                                │
│   [netmaker] 2022-03-24 02:05:38 forwarding coredns traffic from host port 53 to container port 53                                                                                                               │
│   [netmaker] Fatal: Unable to initialize iptables on host: lookup coredns on 10.89.3.1:53: no such host                                                                                                          │

```

**Comment by runbmp** [comment]
Final update, sorry, but hopefully the thread is useful to read.

Issues when running rootless podman (perhaps rootless docker as well)
1) More of a general issue, but I think the documentation should explicitly mention that `dns` should not be part of `PORT_FORWARD_SERVICES` if `DNS_MODE` is off.  They currently say its recommended (https://github.com/gravitl/netmaker-docs/blob/f527549800c942dea5f02f59c0e11b2b11212360/_build/html/server-installation.html#L731)

2) Likewise to 1), ssh should be clarified as well above.  I don't understand how I could turn that on and still use `openssh` outside of the netmaker network.  And if its turned on, what does that really mean?

3) The `docker.io/eclipse-mosquitto:2.0.14` image works great with the `user: 1000:1002` directive.  The other two images do not.  `netmaker-ui` returns `/docker-entrypoint.sh: line 2: can't create /usr/share/nginx/html/config.js: Permission denied` and `netmaker` returns `{"msg":"exec container process /root//./netmaker: Permission denied","level":"error","time":"2022-03-24T02:28:15.000840831Z"}`

It is quite the nice feature these days in containers to provide `PUID` and `PGID` environment variables.  See photoprism for example https://github.com/photoprism/photoprism/blob/cb89a1a189aede610d4f8c7455232d299c1a4dca/scripts/dist/entrypoint-init.sh#L37-L61

4) Neither the `netmaker` or `netmaker-ui` image respond to `podman-compose down` well.  `netmaker-ui` says
```
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.0.1
** excluding:  set()
podman stop -t 10 netmaker-ui
podman-comopsepanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55c4fdbf79db]

goroutine 28 [running]:
os.(*File).Name(...)
	os/file.go:57
github.com/containers/podman/v4/pkg/errorhandling.CloseQuiet(0xc000b01068)
	github.com/containers/podman/v4/pkg/errorhandling/errorhandling.go:74 +0x5b
github.com/containers/podman/v4/libpod.(*Runtime).setupRootlessPortMappingViaRLK(0xc000a6c4e0, 0xc000b54120, {0xc000526480, 0x3f}, 0xc000b59cf0)
	github.com/containers/podman/v4/libpod/networking_slirp4netns.go:559 +0xa36
github.com/containers/podman/v4/libpod.(*Container).handleRestartPolicy(0xc000b54120, {0x55c4fee10e98, 0xc000136020})
	github.com/containers/podman/v4/libpod/container_internal.go:303 +0x49a
github.com/containers/podman/v4/libpod.(*Container).Cleanup(0xc000b54120, {0x55c4fee10e98, 0xc000136020})
	github.com/containers/podman/v4/libpod/container_api.go:617 +0x16a
github.com/containers/podman/v4/pkg/domain/infra/abi.(*ContainerEngine).ContainerStop.func1(0xc000b54120)
	github.com/containers/podman/v4/pkg/domain/infra/abi/containers.go:181 +0x27c
github.com/containers/podman/v4/pkg/parallel/ctr.ContainerOp.func1()
	github.com/containers/podman/v4/pkg/parallel/ctr/ctr.go:28 +0x22
github.com/containers/podman/v4/pkg/parallel.Enqueue.func1()
	github.com/containers/podman/v4/pkg/parallel/parallel.go:66 +0x190
created by github.com/containers/podman/v4/pkg/parallel.Enqueue
	github.com/containers/podman/v4/pkg/parallel/parallel.go:55 +0xc5
exit code: 2
podman rm netmaker-ui
 f98f2d709fb7fcaf51426205fbacb2db12a22e03d5444d9c98b879617d4ad483
exit code: 0
podman pod rm pod_netmaker
Error: pod 58ab60fd43be9366e83fc73100c911c7a8c909bd856b652d5020269474d946e8 has containers that are not ready to be removed: cannot remove container 7282cfa14d43d0c701f2a27a3837dd0e8dfc357ea8f266470cef6ca249215226 as it is running - running or paused containers cannot be removed without force: container state improper
exit code: 125
```
and `netmaker` says:
```
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.0.1
** excluding:  set()
podman stop -t 10 mq
mq
exit code: 0
podman stop -t 10 netmaker
WARN[0010] StopSignal SIGTERM failed to stop container netmaker in 10 seconds, resorting to SIGKILL
netmaker
exit code: 0
```

I will continue testing the functionality of this product with rootless podman, but for now the `pod` with all 3 images is now up and running and I am about to login into the webui for the first time!

**Comment by runbmp** [comment]
I hit a new error that I cannot get past when attempting to create a key:
```
[netmaker] 2022-03-24 02:47:45 connecting to sqlite
[netmaker] 2022-03-24 02:47:45 database successfully connected
[netmaker] 2022-03-24 02:47:45 no OAuth provider found or not configured, continuing without OAuth
[netmaker] 2022-03-24 02:47:45 setting iptables forward policy
[netmaker] 2022-03-24 02:47:45 forwarding mq traffic from host port 1883 to container port 1883
[netmaker] 2022-03-24 02:47:47 Agent Server successfully started on port  50051 (gRPC)
[netmaker] 2022-03-24 02:47:47 REST Server successfully started on port  8081  (REST)
[netmaker] 2022-03-24 02:47:47 connecting to mq broker at mq:1883
[netmaker] 2022-03-24 02:48:00 admin was authenticated
[netmaker] 2022-03-24 02:48:00 admin fetched users
[netmaker] 2022-03-24 02:48:00 admin fetched networks.
[netmaker] 2022-03-24 02:48:00 admin fetched all nodes they have access to
[netmaker] 2022-03-24 02:48:08 admin fetched all nodes they have access to
[netmaker] 2022-03-24 02:48:15 admin fetched all nodes they have access to
[netmaker] 2022-03-24 02:48:16 processed request error: could not retrieve comms netid
```

I don't know go or sqlite at all really, but from what I can tell, the db connected and was supposed to create all the necessary tables.  However, after ssh'ing into the container and installing sqlite, I can see the tables:
```
sqlite> .tables
deletednodes  generated     nodes         serveruuid
dns           networks      peers         users
extclients    nodeacls      serverconf
```
Additionally, I can see the network I just made in the table:
```
sqlite> SELECT * FROM networks;
mesh-vpn|{"addressrange":"10.11.12.0/24","addressrange6":"","netid":"mesh-vpn","nodeslastmodified":1648089727,"networklastmodified":1648089725,"defaultinterface":"nm-mesh-vpn","defaultlistenport":51821,"nodelimit":999999999,"defaultpostup":"","defaultpostdown":"","defaultkeepalive":20,"accesskeys":[],"allowmanualsignup":"no","islocal":"no","isdualstack":"no","isipv4":"yes","isipv6":"no","ispointtosite":"no","iscomms":"no","localrange":"","defaultudpholepunch":"yes","defaultextclientdns":"","defaultmtu":1280,"defaultserveraddrs":null,"defaultacl":"yes"}
```

As you can see, I have no `nm-comms-id`, I think this is due to have client mode turned off: https://github.com/gravitl/netmaker/blob/3a4ece1960226a1ea9252a6e2820d1832ab00533/main.go#L74-L89

This means if you have client mode turned off you can't create an access key?

**Comment by afeiszli** [comment]
@runbmp thank you for all this work. It would be great to see Netmaker running in podman, and apologies for all the issues setting this up.

CLIENT_MODE=off is deprecated; the server really will not function properly today without client mode. We need to updated the documentation to point this out.

**Comment by afeiszli** [comment]
@runbmp update on this. CLIENT_MODE should be usable again after our architecture change in 0.13. The comms network is also gone now, so there should be no issue with your implementation.

**Comment by afeiszli** [comment]
Closing since no response from user.
